/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './not-found.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/router/src/directives/router_link';
import * as import12 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
export class Wrapper_NotFoundComponent {
  context:import0.NotFoundComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.NotFoundComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
const nodeDebugInfos_NotFoundComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import0.NotFoundComponent],import0.NotFoundComponent,{})];
var renderType_NotFoundComponent_Host:import3.RenderComponentType = (null as any);
class _View_NotFoundComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _NotFoundComponent_0_4:Wrapper_NotFoundComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_NotFoundComponent_Host0,renderType_NotFoundComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_NotFoundComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = import5.selectOrCreateRenderHostElement(this.renderer,'dcs-not-found',import5.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NotFoundComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NotFoundComponent_0_4 = new Wrapper_NotFoundComponent();
    this._appEl_0.initComponent(this._NotFoundComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._NotFoundComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.NotFoundComponent) && (0 === requestNodeIndex))) { return this._NotFoundComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._NotFoundComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._NotFoundComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NotFoundComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import1.AppView<any> {
  if ((renderType_NotFoundComponent_Host === (null as any))) { (renderType_NotFoundComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_NotFoundComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const NotFoundComponentNgFactory:import10.ComponentFactory<import0.NotFoundComponent> = new import10.ComponentFactory<import0.NotFoundComponent>('dcs-not-found',viewFactory_NotFoundComponent_Host0,import0.NotFoundComponent);
const styles_NotFoundComponent:any[] = ([] as any[]);
const nodeDebugInfos_NotFoundComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import11.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_NotFoundComponent:import3.RenderComponentType = (null as any);
class _View_NotFoundComponent0 extends import1.DebugAppView<import0.NotFoundComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _RouterLinkWithHref_9_3:import12.Wrapper_RouterLinkWithHref;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_NotFoundComponent0,renderType_NotFoundComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_NotFoundComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import5.createRenderElement(this.renderer,parentRenderNode,'div',new import5.InlineArray2(2,'class','row'),this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',this.debug(1,0,17));
    this._el_2 = import5.createRenderElement(this.renderer,this._el_0,'div',new import5.InlineArray2(2,'class','col-sm-12'),this.debug(2,1,2));
    this._text_3 = this.renderer.createText(this._el_2,'\n\n    ',this.debug(3,1,25));
    this._el_4 = import5.createRenderElement(this.renderer,this._el_2,'h1',import5.EMPTY_INLINE_ARRAY,this.debug(4,3,4));
    this._text_5 = this.renderer.createText(this._el_4,'Page not found',this.debug(5,3,8));
    this._text_6 = this.renderer.createText(this._el_2,'\n\n    ',this.debug(6,3,27));
    this._el_7 = import5.createRenderElement(this.renderer,this._el_2,'p',import5.EMPTY_INLINE_ARRAY,this.debug(7,5,4));
    this._text_8 = this.renderer.createText(this._el_7,'\n      Please return to the\n      ',this.debug(8,5,7));
    this._el_9 = import5.createRenderElement(this.renderer,this._el_7,'a',new import5.InlineArray2(2,'routerLink','/'),this.debug(9,7,6));
    this._RouterLinkWithHref_9_3 = new import12.Wrapper_RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_10 = this.renderer.createText(this._el_9,'Homepage',this.debug(10,7,24));
    this._text_11 = this.renderer.createText(this._el_7,'.\n    ',this.debug(11,7,36));
    this._text_12 = this.renderer.createText(this._el_2,'\n\n  ',this.debug(12,8,8));
    this._text_13 = this.renderer.createText(this._el_0,'\n',this.debug(13,10,8));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n',this.debug(14,11,6));
    var disposable_0:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.RouterLinkWithHref) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._RouterLinkWithHref_9_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(9,7,9);
    const currVal_9_0_0:any = '/';
    this._RouterLinkWithHref_9_3.check_routerLink(currVal_9_0_0,throwOnChange,false);
    this._RouterLinkWithHref_9_3.detectChangesInInputProps(this,this._el_9,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RouterLinkWithHref_9_3.detectChangesInHostProps(this,this._el_9,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(9,7,6);
    this._RouterLinkWithHref_9_3.context.ngOnDestroy();
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(9,7,6);
    const pd_9_0:any = ((<any>this._RouterLinkWithHref_9_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_9_0);
  }
}
export function viewFactory_NotFoundComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import1.AppView<import0.NotFoundComponent> {
  if ((renderType_NotFoundComponent === (null as any))) { (renderType_NotFoundComponent = viewUtils.createRenderComponentType('/Users/peterdickten/versioned/dcs-food-order/src/app/not-found/not-found.component.html',0,import9.ViewEncapsulation.None,styles_NotFoundComponent,{})); }
  return new _View_NotFoundComponent0(viewUtils,parentInjector,declarationEl);
}