/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './products-list.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/debug_context';
import * as import5 from '@angular/core/src/render/api';
import * as import6 from '@angular/core/src/linker/element';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/core/src/linker/template_ref';
import * as import12 from '@angular/common/src/directives/ng_for';
import * as import13 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import14 from '../../shared/pipes/Price.pipe';
import * as import15 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import16 from '@angular/router/src/directives/router_link';
import * as import17 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import18 from '@angular/router/src/router';
import * as import19 from '@angular/router/src/router_state';
import * as import20 from '@angular/common/src/location/location_strategy';
export class Wrapper_ProductsListComponent {
  context:import0.ProductsListComponent;
  changed:boolean;
  /*private*/ _expr_0:any;
  constructor() {
    this.changed = false;
    this.context = new import0.ProductsListComponent();
    this._expr_0 = import1.UNINITIALIZED;
  }
  check_products(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this.changed = true;
      this.context.products = currValue;
      this._expr_0 = currValue;
    }
  }
  detectChangesInInputProps(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import3.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
const nodeDebugInfos_ProductsListComponent_Host0:import4.StaticNodeDebugInfo[] = [new import4.StaticNodeDebugInfo([import0.ProductsListComponent],import0.ProductsListComponent,{})];
var renderType_ProductsListComponent_Host:import5.RenderComponentType = (null as any);
class _View_ProductsListComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import6.AppElement;
  _ProductsListComponent_0_4:Wrapper_ProductsListComponent;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement) {
    super(_View_ProductsListComponent_Host0,renderType_ProductsListComponent_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ProductsListComponent_Host0);
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = import2.selectOrCreateRenderHostElement(this.renderer,'dcs-products-list',import2.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import6.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ProductsListComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ProductsListComponent_0_4 = new Wrapper_ProductsListComponent();
    this._appEl_0.initComponent(this._ProductsListComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ProductsListComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ProductsListComponent) && (0 === requestNodeIndex))) { return this._ProductsListComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._ProductsListComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._ProductsListComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProductsListComponent_Host0(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement):import3.AppView<any> {
  if ((renderType_ProductsListComponent_Host === (null as any))) { (renderType_ProductsListComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ProductsListComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ProductsListComponentNgFactory:import10.ComponentFactory<import0.ProductsListComponent> = new import10.ComponentFactory<import0.ProductsListComponent>('dcs-products-list',viewFactory_ProductsListComponent_Host0,import0.ProductsListComponent);
const styles_ProductsListComponent:any[] = ([] as any[]);
const nodeDebugInfos_ProductsListComponent0:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import11.TemplateRef,
    import12.NgFor
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_ProductsListComponent:import5.RenderComponentType = (null as any);
class _View_ProductsListComponent0 extends import3.DebugAppView<import0.ProductsListComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _appEl_22:import6.AppElement;
  _TemplateRef_22_5:any;
  _NgFor_22_6:import13.Wrapper_NgFor;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _pipe_dcsPrice_0:import14.PricePipe;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement) {
    super(_View_ProductsListComponent0,renderType_ProductsListComponent,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ProductsListComponent0);
  }
  createInternal(rootSelector:string):import6.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import2.createRenderElement(this.renderer,parentRenderNode,'table',new import2.InlineArray2(2,'class','table table-striped table-bordered table-hover'),this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',this.debug(1,0,62));
    this._el_2 = import2.createRenderElement(this.renderer,this._el_0,'thead',import2.EMPTY_INLINE_ARRAY,this.debug(2,1,2));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',this.debug(3,1,9));
    this._el_4 = import2.createRenderElement(this.renderer,this._el_2,'tr',import2.EMPTY_INLINE_ARRAY,this.debug(4,2,4));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',this.debug(5,2,8));
    this._el_6 = import2.createRenderElement(this.renderer,this._el_4,'th',import2.EMPTY_INLINE_ARRAY,this.debug(6,3,6));
    this._text_7 = this.renderer.createText(this._el_6,'Article ID',this.debug(7,3,10));
    this._text_8 = this.renderer.createText(this._el_4,'\n      ',this.debug(8,3,25));
    this._el_9 = import2.createRenderElement(this.renderer,this._el_4,'th',import2.EMPTY_INLINE_ARRAY,this.debug(9,4,6));
    this._text_10 = this.renderer.createText(this._el_9,'Label',this.debug(10,4,10));
    this._text_11 = this.renderer.createText(this._el_4,'\n      ',this.debug(11,4,20));
    this._el_12 = import2.createRenderElement(this.renderer,this._el_4,'th',import2.EMPTY_INLINE_ARRAY,this.debug(12,5,6));
    this._text_13 = this.renderer.createText(this._el_12,'Price',this.debug(13,5,10));
    this._text_14 = this.renderer.createText(this._el_4,'\n      ',this.debug(14,5,20));
    this._el_15 = import2.createRenderElement(this.renderer,this._el_4,'th',import2.EMPTY_INLINE_ARRAY,this.debug(15,6,6));
    this._text_16 = this.renderer.createText(this._el_15,' ',this.debug(16,6,10));
    this._text_17 = this.renderer.createText(this._el_4,'\n    ',this.debug(17,6,21));
    this._text_18 = this.renderer.createText(this._el_2,'\n  ',this.debug(18,7,9));
    this._text_19 = this.renderer.createText(this._el_0,'\n\n  ',this.debug(19,8,10));
    this._el_20 = import2.createRenderElement(this.renderer,this._el_0,'tbody',import2.EMPTY_INLINE_ARRAY,this.debug(20,10,2));
    this._text_21 = this.renderer.createText(this._el_20,'\n    ',this.debug(21,10,9));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_20,this.debug(22,11,4));
    this._appEl_22 = new import6.AppElement(22,20,this,this._anchor_22);
    this._TemplateRef_22_5 = new import11.TemplateRef_(this._appEl_22,viewFactory_ProductsListComponent1);
    this._NgFor_22_6 = new import13.Wrapper_NgFor(this._appEl_22.vcRef,this._TemplateRef_22_5,this.parentInjector.get(import15.IterableDiffers),this.ref);
    this._text_23 = this.renderer.createText(this._el_20,'\n  ',this.debug(23,19,9));
    this._text_24 = this.renderer.createText(this._el_0,'\n',this.debug(24,20,10));
    this._text_25 = this.renderer.createText(parentRenderNode,'\n',this.debug(25,21,8));
    this.debug((null as any),(null as any),(null as any));
    this._pipe_dcsPrice_0 = new import14.PricePipe();
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._text_24,
      this._text_25
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import12.NgFor) && (22 === requestNodeIndex))) { return this._NgFor_22_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(22,11,8);
    const currVal_22_0_0:any = this.context.products;
    this._NgFor_22_6.check_ngForOf(currVal_22_0_0,throwOnChange,false);
    this.debug(22,11,8);
    const currVal_22_0_1:any = this.context.identity;
    this._NgFor_22_6.check_ngForTrackBy(currVal_22_0_1,throwOnChange,false);
    this._NgFor_22_6.detectChangesInInputProps(this,this._anchor_22,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ProductsListComponent0(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement):import3.AppView<import0.ProductsListComponent> {
  if ((renderType_ProductsListComponent === (null as any))) { (renderType_ProductsListComponent = viewUtils.createRenderComponentType('/Users/peterdickten/versioned/dcs-food-order/src/app/products/products-list/products-list.component.html',0,import9.ViewEncapsulation.None,styles_ProductsListComponent,{})); }
  return new _View_ProductsListComponent0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_ProductsListComponent1:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([import16.RouterLinkWithHref],(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class _View_ProductsListComponent1 extends import3.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _RouterLinkWithHref_13_3:import17.Wrapper_RouterLinkWithHref;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  _pipe_dcsPrice_0_0:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement) {
    super(_View_ProductsListComponent1,renderType_ProductsListComponent,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_ProductsListComponent1);
    this._expr_21 = import1.UNINITIALIZED;
    this._expr_22 = import1.UNINITIALIZED;
    this._expr_23 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = import2.createRenderElement(this.renderer,(null as any),'tr',import2.EMPTY_INLINE_ARRAY,this.debug(0,11,4));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',this.debug(1,11,60));
    this._el_2 = import2.createRenderElement(this.renderer,this._el_0,'td',import2.EMPTY_INLINE_ARRAY,this.debug(2,12,6));
    this._text_3 = this.renderer.createText(this._el_2,'',this.debug(3,12,10));
    this._text_4 = this.renderer.createText(this._el_0,'\n      ',this.debug(4,12,45));
    this._el_5 = import2.createRenderElement(this.renderer,this._el_0,'td',import2.EMPTY_INLINE_ARRAY,this.debug(5,13,6));
    this._text_6 = this.renderer.createText(this._el_5,'',this.debug(6,13,10));
    this._text_7 = this.renderer.createText(this._el_0,'\n      ',this.debug(7,13,41));
    this._el_8 = import2.createRenderElement(this.renderer,this._el_0,'td',import2.EMPTY_INLINE_ARRAY,this.debug(8,14,6));
    this._text_9 = this.renderer.createText(this._el_8,'',this.debug(9,14,10));
    this._text_10 = this.renderer.createText(this._el_0,'\n      ',this.debug(10,14,52));
    this._el_11 = import2.createRenderElement(this.renderer,this._el_0,'td',import2.EMPTY_INLINE_ARRAY,this.debug(11,15,6));
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',this.debug(12,15,10));
    this._el_13 = import2.createRenderElement(this.renderer,this._el_11,'a',new import2.InlineArray4(4,'class','btn btn-default','type','button'),this.debug(13,16,8));
    this._RouterLinkWithHref_13_3 = new import17.Wrapper_RouterLinkWithHref(this.parent.parentInjector.get(import18.Router),this.parent.parentInjector.get(import19.ActivatedRoute),this.parent.parentInjector.get(import20.LocationStrategy));
    this._text_14 = this.renderer.createText(this._el_13,'edit',this.debug(14,16,96));
    this._text_15 = this.renderer.createText(this._el_11,'\n        ',this.debug(15,16,104));
    this._el_16 = import2.createRenderElement(this.renderer,this._el_11,'button',new import2.InlineArray4(4,'class','btn btn-danger','type','button'),this.debug(16,17,8));
    this._text_17 = this.renderer.createText(this._el_16,'delete',this.debug(17,17,86));
    this._text_18 = this.renderer.createText(this._el_11,'\n      ',this.debug(18,17,101));
    this._text_19 = this.renderer.createText(this._el_0,'\n    ',this.debug(19,18,11));
    this._pipe_dcsPrice_0_0 = import2.pureProxy1((<_View_ProductsListComponent0>this.parent)._pipe_dcsPrice_0.transform.bind((<_View_ProductsListComponent0>this.parent)._pipe_dcsPrice_0));
    var disposable_0:Function = this.renderer.listen(this._el_13,'click',this.eventHandler(this._handle_click_13_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_16,'click',this.eventHandler(this._handle_click_16_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.RouterLinkWithHref) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._RouterLinkWithHref_13_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    this.debug(13,16,49);
    const currVal_13_0_0:any = import2.interpolate(1,'/products/',this.context.$implicit.get('id'),'');
    this._RouterLinkWithHref_13_3.check_routerLink(currVal_13_0_0,throwOnChange,false);
    this._RouterLinkWithHref_13_3.detectChangesInInputProps(this,this._el_13,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(3,12,10);
    const currVal_21:any = import2.interpolate(1,'',this.context.$implicit.get('articleId'),'');
    if (import2.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setText(this._text_3,currVal_21);
      this._expr_21 = currVal_21;
    }
    this.debug(6,13,10);
    const currVal_22:any = import2.interpolate(1,'',this.context.$implicit.get('label'),'');
    if (import2.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setText(this._text_6,currVal_22);
      this._expr_22 = currVal_22;
    }
    this.debug(9,14,10);
    valUnwrapper.reset();
    const currVal_23:any = import2.interpolate(1,'',valUnwrapper.unwrap(import2.castByValue(this._pipe_dcsPrice_0_0,(<_View_ProductsListComponent0>this.parent)._pipe_dcsPrice_0.transform)(this.context.$implicit.get('price'))),'');
    if ((valUnwrapper.hasWrappedValue || import2.checkBinding(throwOnChange,this._expr_23,currVal_23))) {
      this.renderer.setText(this._text_9,currVal_23);
      this._expr_23 = currVal_23;
    }
    this._RouterLinkWithHref_13_3.detectChangesInHostProps(this,this._el_13,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(13,16,8);
    this._RouterLinkWithHref_13_3.context.ngOnDestroy();
  }
  private _handle_click_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(13,16,8);
    const pd_13_0:any = ((<any>this._RouterLinkWithHref_13_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_13_0);
  }
  private _handle_click_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(16,17,53);
    const pd_16_0:any = ((<any>this.parent.context.onDelete.next(this.context.$implicit)) !== false);
    return (true && pd_16_0);
  }
}
function viewFactory_ProductsListComponent1(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement):import3.AppView<any> {
  return new _View_ProductsListComponent1(viewUtils,parentInjector,declarationEl);
}