/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './order-page.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from 'ng2-redux/lib/components/ng-redux';
import * as import10 from '../backend/order/order.actions';
import * as import11 from '../../products/backend/products/products.actions';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../order-form/order-form.component';
import * as import15 from '../order-totals/order-totals.component';
import * as import16 from '../order-form/order-form.component.ngfactory';
import * as import17 from '../order-totals/order-totals.component.ngfactory';
import * as import18 from '@angular/common/src/pipes/async_pipe';
import * as import19 from '@angular/forms/src/form_builder';
export class Wrapper_OrderPageComponent {
  context:import0.OrderPageComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.OrderPageComponent(p0,p1,p2);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
const nodeDebugInfos_OrderPageComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import0.OrderPageComponent],import0.OrderPageComponent,{})];
var renderType_OrderPageComponent_Host:import3.RenderComponentType = (null as any);
class _View_OrderPageComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _OrderPageComponent_0_4:Wrapper_OrderPageComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_OrderPageComponent_Host0,renderType_OrderPageComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OrderPageComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = import5.selectOrCreateRenderHostElement(this.renderer,'dcs-order-page',import5.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_OrderPageComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._OrderPageComponent_0_4 = new Wrapper_OrderPageComponent(this.parentInjector.get(import9.NgRedux),this.parentInjector.get(import10.OrderActions),this.parentInjector.get(import11.ProductsActions));
    this._appEl_0.initComponent(this._OrderPageComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._OrderPageComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.OrderPageComponent) && (0 === requestNodeIndex))) { return this._OrderPageComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._OrderPageComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._OrderPageComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_OrderPageComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import1.AppView<any> {
  if ((renderType_OrderPageComponent_Host === (null as any))) { (renderType_OrderPageComponent_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_OrderPageComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const OrderPageComponentNgFactory:import13.ComponentFactory<import0.OrderPageComponent> = new import13.ComponentFactory<import0.OrderPageComponent>('dcs-order-page',viewFactory_OrderPageComponent_Host0,import0.OrderPageComponent);
const styles_OrderPageComponent:any[] = ([] as any[]);
const nodeDebugInfos_OrderPageComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import14.OrderFormComponent],import14.OrderFormComponent,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import15.OrderTotalsComponent],import15.OrderTotalsComponent,{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_OrderPageComponent:import3.RenderComponentType = (null as any);
class _View_OrderPageComponent0 extends import1.DebugAppView<import0.OrderPageComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import4.AppElement;
  _OrderFormComponent_7_4:import16.Wrapper_OrderFormComponent;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import4.AppElement;
  _OrderTotalsComponent_12_4:import17.Wrapper_OrderTotalsComponent;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _pipe_async_0:import18.AsyncPipe;
  _pipe_async_1:import18.AsyncPipe;
  _pipe_async_2:import18.AsyncPipe;
  _pipe_async_3:import18.AsyncPipe;
  _pipe_async_4:import18.AsyncPipe;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_OrderPageComponent0,renderType_OrderPageComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OrderPageComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import5.createRenderElement(this.renderer,parentRenderNode,'div',new import5.InlineArray2(2,'class','row'),this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',this.debug(1,0,17));
    this._el_2 = import5.createRenderElement(this.renderer,this._el_0,'div',new import5.InlineArray2(2,'class','col-sm-12'),this.debug(2,1,2));
    this._text_3 = this.renderer.createText(this._el_2,'\n\n    ',this.debug(3,1,25));
    this._el_4 = import5.createRenderElement(this.renderer,this._el_2,'h1',import5.EMPTY_INLINE_ARRAY,this.debug(4,3,4));
    this._text_5 = this.renderer.createText(this._el_4,'Order',this.debug(5,3,8));
    this._text_6 = this.renderer.createText(this._el_2,'\n\n    ',this.debug(6,3,18));
    this._el_7 = import5.createRenderElement(this.renderer,this._el_2,'dcs-order-form',import5.EMPTY_INLINE_ARRAY,this.debug(7,5,4));
    this._appEl_7 = new import4.AppElement(7,2,this,this._el_7);
    var compView_7:any = import16.viewFactory_OrderFormComponent0(this.viewUtils,this.injector(7),this._appEl_7);
    this._OrderFormComponent_7_4 = new import16.Wrapper_OrderFormComponent(this.parentInjector.get(import19.FormBuilder));
    this._appEl_7.initComponent(this._OrderFormComponent_7_4.context,([] as any[]),compView_7);
    compView_7.create(this._OrderFormComponent_7_4.context,([] as any[]),(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n\n    ',this.debug(8,10,22));
    this._el_9 = import5.createRenderElement(this.renderer,this._el_2,'h2',import5.EMPTY_INLINE_ARRAY,this.debug(9,12,4));
    this._text_10 = this.renderer.createText(this._el_9,'Totals',this.debug(10,12,8));
    this._text_11 = this.renderer.createText(this._el_2,'\n\n    ',this.debug(11,12,19));
    this._el_12 = import5.createRenderElement(this.renderer,this._el_2,'dcs-order-totals',import5.EMPTY_INLINE_ARRAY,this.debug(12,14,4));
    this._appEl_12 = new import4.AppElement(12,2,this,this._el_12);
    var compView_12:any = import17.viewFactory_OrderTotalsComponent0(this.viewUtils,this.injector(12),this._appEl_12);
    this._OrderTotalsComponent_12_4 = new import17.Wrapper_OrderTotalsComponent();
    this._appEl_12.initComponent(this._OrderTotalsComponent_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),'\n    ',this.debug(13,17,5));
    compView_12.create(this._OrderTotalsComponent_12_4.context,([] as any[]),(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n\n\n  ',this.debug(14,18,23));
    this._text_15 = this.renderer.createText(this._el_0,'\n',this.debug(15,21,8));
    this._text_16 = this.renderer.createText(parentRenderNode,'\n\n\n\n',this.debug(16,22,6));
    var disposable_0:Function = this.renderer.listen(this._el_7,'onOrderChanged',this.eventHandler(this._handle_onOrderChanged_7_0.bind(this)));
    this.debug((null as any),(null as any),(null as any));
    this._pipe_async_0 = new import18.AsyncPipe(this.ref);
    this._pipe_async_1 = new import18.AsyncPipe(this.ref);
    this._pipe_async_2 = new import18.AsyncPipe(this.ref);
    const subscription_0:any = this._OrderFormComponent_7_4.context.onOrderChanged.subscribe(this.eventHandler(this._handle_onOrderChanged_7_0.bind(this)));
    this._pipe_async_3 = new import18.AsyncPipe(this.ref);
    this._pipe_async_4 = new import18.AsyncPipe(this.ref);
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.OrderFormComponent) && (7 === requestNodeIndex))) { return this._OrderFormComponent_7_4.context; }
    if (((token === import15.OrderTotalsComponent) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._OrderTotalsComponent_12_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import8.ValueUnwrapper();
    this.debug(7,6,6);
    valUnwrapper.reset();
    const currVal_7_0_0:any = valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.order$));
    this._OrderFormComponent_7_4.check_order(currVal_7_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this.debug(7,7,6);
    valUnwrapper.reset();
    const currVal_7_0_1:any = valUnwrapper.unwrap(this._pipe_async_1.transform(this.context.orderLoaded$));
    this._OrderFormComponent_7_4.check_orderLoaded(currVal_7_0_1,throwOnChange,valUnwrapper.hasWrappedValue);
    this.debug(7,8,6);
    valUnwrapper.reset();
    const currVal_7_0_2:any = valUnwrapper.unwrap(this._pipe_async_2.transform(this.context.products$));
    this._OrderFormComponent_7_4.check_products(currVal_7_0_2,throwOnChange,valUnwrapper.hasWrappedValue);
    this._OrderFormComponent_7_4.detectChangesInInputProps(this,this._el_7,throwOnChange);
    this.debug(12,15,6);
    valUnwrapper.reset();
    const currVal_12_0_0:any = valUnwrapper.unwrap(this._pipe_async_3.transform(this.context.orderTotalsByUser$));
    this._OrderTotalsComponent_12_4.check_orderTotalsByUser(currVal_12_0_0,throwOnChange,valUnwrapper.hasWrappedValue);
    this.debug(12,16,6);
    valUnwrapper.reset();
    const currVal_12_0_1:any = valUnwrapper.unwrap(this._pipe_async_4.transform(this.context.orderTotal$));
    this._OrderTotalsComponent_12_4.check_orderTotal(currVal_12_0_1,throwOnChange,valUnwrapper.hasWrappedValue);
    this._OrderTotalsComponent_12_4.detectChangesInInputProps(this,this._el_12,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._OrderFormComponent_7_4.detectChangesInHostProps(this,this._el_7,throwOnChange);
    this._OrderTotalsComponent_12_4.detectChangesInHostProps(this,this._el_12,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(12,14,4);
    this._pipe_async_0.ngOnDestroy();
    this._pipe_async_1.ngOnDestroy();
    this._pipe_async_2.ngOnDestroy();
    this._pipe_async_3.ngOnDestroy();
    this._pipe_async_4.ngOnDestroy();
  }
  private _handle_onOrderChanged_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(7,9,6);
    const pd_7_0:any = ((<any>this.context.updateOrder($event)) !== false);
    return (true && pd_7_0);
  }
}
export function viewFactory_OrderPageComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import1.AppView<import0.OrderPageComponent> {
  if ((renderType_OrderPageComponent === (null as any))) { (renderType_OrderPageComponent = viewUtils.createRenderComponentType('/Users/peterdickten/versioned/dcs-food-order/src/app/order/order-page/order-page.component.html',0,import12.ViewEncapsulation.None,styles_OrderPageComponent,{})); }
  return new _View_OrderPageComponent0(viewUtils,parentInjector,declarationEl);
}