/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './order-form.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/debug_context';
import * as import5 from '@angular/core/src/render/api';
import * as import6 from '@angular/core/src/linker/element';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/forms/src/form_builder';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '@angular/common/src/directives/ng_for';
import * as import14 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import15 from '../../shared/pipes/Price.pipe';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import18 from '@angular/forms/src/directives/control_container';
import * as import19 from '@angular/forms/src/directives/ng_control_status';
import * as import20 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import21 from '@angular/forms/src/directives/control_value_accessor';
import * as import22 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import23 from '@angular/forms/src/directives/ng_control';
import * as import24 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import25 from '@angular/forms/src/directives/default_value_accessor';
import * as import26 from '@angular/forms/src/directives/number_value_accessor';
import * as import27 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import28 from '../../../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import29 from '../../../../node_modules/@angular/forms/src/directives/select_control_value_accessor.ngfactory';
import * as import30 from '../../../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import31 from '../../../../node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.ngfactory';
import * as import32 from '../../../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import33 from '../../../../node_modules/@angular/forms/src/directives/number_value_accessor.ngfactory';
import * as import34 from '@angular/core/src/linker/element_ref';
export class Wrapper_OrderFormComponent {
  context:import0.OrderFormComponent;
  changed:boolean;
  changes:{[key: string]:any};
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(p0:any) {
    this.changed = false;
    this.changes = {};
    this.context = new import0.OrderFormComponent(p0);
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
    this._expr_2 = import1.UNINITIALIZED;
  }
  check_order(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this.changed = true;
      this.context.order = currValue;
      this.changes['order'] = new import1.SimpleChange(this._expr_0,currValue);
      this._expr_0 = currValue;
    }
  }
  check_orderLoaded(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this.changed = true;
      this.context.orderLoaded = currValue;
      this.changes['orderLoaded'] = new import1.SimpleChange(this._expr_1,currValue);
      this._expr_1 = currValue;
    }
  }
  check_products(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._expr_2,currValue))) {
      this.changed = true;
      this.context.products = currValue;
      this.changes['products'] = new import1.SimpleChange(this._expr_2,currValue);
      this._expr_2 = currValue;
    }
  }
  detectChangesInInputProps(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if (changed) {
      this.context.ngOnChanges(this.changes);
      this.changes = {};
    } }
    return changed;
  }
  detectChangesInHostProps(view:import3.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
const nodeDebugInfos_OrderFormComponent_Host0:import4.StaticNodeDebugInfo[] = [new import4.StaticNodeDebugInfo([import0.OrderFormComponent],import0.OrderFormComponent,{})];
var renderType_OrderFormComponent_Host:import5.RenderComponentType = (null as any);
class _View_OrderFormComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import6.AppElement;
  _OrderFormComponent_0_4:Wrapper_OrderFormComponent;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement) {
    super(_View_OrderFormComponent_Host0,renderType_OrderFormComponent_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OrderFormComponent_Host0);
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = import2.selectOrCreateRenderHostElement(this.renderer,'dcs-order-form',import2.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import6.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_OrderFormComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._OrderFormComponent_0_4 = new Wrapper_OrderFormComponent(this.parentInjector.get(import9.FormBuilder));
    this._appEl_0.initComponent(this._OrderFormComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._OrderFormComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.OrderFormComponent) && (0 === requestNodeIndex))) { return this._OrderFormComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._OrderFormComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._OrderFormComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_OrderFormComponent_Host0(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement):import3.AppView<any> {
  if ((renderType_OrderFormComponent_Host === (null as any))) { (renderType_OrderFormComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_OrderFormComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const OrderFormComponentNgFactory:import11.ComponentFactory<import0.OrderFormComponent> = new import11.ComponentFactory<import0.OrderFormComponent>('dcs-order-form',viewFactory_OrderFormComponent_Host0,import0.OrderFormComponent);
const styles_OrderFormComponent:any[] = ([] as any[]);
const nodeDebugInfos_OrderFormComponent0:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import12.TemplateRef,
    import13.NgFor
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_OrderFormComponent:import5.RenderComponentType = (null as any);
class _View_OrderFormComponent0 extends import3.DebugAppView<import0.OrderFormComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import6.AppElement;
  _TemplateRef_27_5:any;
  _NgFor_27_6:import14.Wrapper_NgFor;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _pipe_dcsPrice_0:import15.PricePipe;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement) {
    super(_View_OrderFormComponent0,renderType_OrderFormComponent,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OrderFormComponent0);
  }
  createInternal(rootSelector:string):import6.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import2.createRenderElement(this.renderer,parentRenderNode,'table',new import2.InlineArray2(2,'class','table table-striped table-bordered table-hover'),this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',this.debug(1,0,62));
    this._el_2 = import2.createRenderElement(this.renderer,this._el_0,'thead',import2.EMPTY_INLINE_ARRAY,this.debug(2,1,2));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',this.debug(3,1,9));
    this._el_4 = import2.createRenderElement(this.renderer,this._el_2,'tr',import2.EMPTY_INLINE_ARRAY,this.debug(4,2,4));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',this.debug(5,2,8));
    this._el_6 = import2.createRenderElement(this.renderer,this._el_4,'th',import2.EMPTY_INLINE_ARRAY,this.debug(6,3,6));
    this._text_7 = this.renderer.createText(this._el_6,'User',this.debug(7,3,10));
    this._text_8 = this.renderer.createText(this._el_4,'\n      ',this.debug(8,3,19));
    this._el_9 = import2.createRenderElement(this.renderer,this._el_4,'th',import2.EMPTY_INLINE_ARRAY,this.debug(9,4,6));
    this._text_10 = this.renderer.createText(this._el_9,'Product',this.debug(10,4,10));
    this._text_11 = this.renderer.createText(this._el_4,'\n      ',this.debug(11,4,22));
    this._el_12 = import2.createRenderElement(this.renderer,this._el_4,'th',import2.EMPTY_INLINE_ARRAY,this.debug(12,5,6));
    this._text_13 = this.renderer.createText(this._el_12,'Number of Products',this.debug(13,5,10));
    this._text_14 = this.renderer.createText(this._el_4,'\n      ',this.debug(14,5,33));
    this._el_15 = import2.createRenderElement(this.renderer,this._el_4,'th',import2.EMPTY_INLINE_ARRAY,this.debug(15,6,6));
    this._text_16 = this.renderer.createText(this._el_15,'Price for Single Item',this.debug(16,6,10));
    this._text_17 = this.renderer.createText(this._el_4,'\n      ',this.debug(17,6,36));
    this._el_18 = import2.createRenderElement(this.renderer,this._el_4,'th',import2.EMPTY_INLINE_ARRAY,this.debug(18,7,6));
    this._text_19 = this.renderer.createText(this._el_18,'Price for all Items',this.debug(19,7,10));
    this._text_20 = this.renderer.createText(this._el_4,'\n      ',this.debug(20,7,34));
    this._el_21 = import2.createRenderElement(this.renderer,this._el_4,'th',import2.EMPTY_INLINE_ARRAY,this.debug(21,8,6));
    this._text_22 = this.renderer.createText(this._el_4,'\n    ',this.debug(22,8,15));
    this._text_23 = this.renderer.createText(this._el_2,'\n  ',this.debug(23,9,9));
    this._text_24 = this.renderer.createText(this._el_0,'\n\n  ',this.debug(24,10,10));
    this._el_25 = import2.createRenderElement(this.renderer,this._el_0,'tbody',import2.EMPTY_INLINE_ARRAY,this.debug(25,12,2));
    this._text_26 = this.renderer.createText(this._el_25,'\n\n    ',this.debug(26,12,9));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_25,this.debug(27,14,4));
    this._appEl_27 = new import6.AppElement(27,25,this,this._anchor_27);
    this._TemplateRef_27_5 = new import12.TemplateRef_(this._appEl_27,viewFactory_OrderFormComponent1);
    this._NgFor_27_6 = new import14.Wrapper_NgFor(this._appEl_27.vcRef,this._TemplateRef_27_5,this.parentInjector.get(import16.IterableDiffers),this.ref);
    this._text_28 = this.renderer.createText(this._el_25,'\n\n  ',this.debug(28,39,9));
    this._text_29 = this.renderer.createText(this._el_0,'\n\n',this.debug(29,41,10));
    this._text_30 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(30,43,8));
    this._el_31 = import2.createRenderElement(this.renderer,parentRenderNode,'button',new import2.InlineArray4(4,'class','btn btn-default','type','button'),this.debug(31,45,0));
    this._text_32 = this.renderer.createText(this._el_31,'Add Item',this.debug(32,45,66));
    this._text_33 = this.renderer.createText(parentRenderNode,'\n',this.debug(33,45,83));
    this.debug((null as any),(null as any),(null as any));
    this._pipe_dcsPrice_0 = new import15.PricePipe();
    var disposable_0:Function = this.renderer.listen(this._el_31,'click',this.eventHandler(this._handle_click_31_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import13.NgFor) && (27 === requestNodeIndex))) { return this._NgFor_27_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(27,14,8);
    const currVal_27_0_0:any = this.context.form.controls;
    this._NgFor_27_6.check_ngForOf(currVal_27_0_0,throwOnChange,false);
    this._NgFor_27_6.detectChangesInInputProps(this,this._anchor_27,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_31_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(31,45,46);
    const pd_31_0:any = ((<any>this.context.addItem()) !== false);
    return (true && pd_31_0);
  }
}
export function viewFactory_OrderFormComponent0(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement):import3.AppView<import0.OrderFormComponent> {
  if ((renderType_OrderFormComponent === (null as any))) { (renderType_OrderFormComponent = viewUtils.createRenderComponentType('/Users/peterdickten/versioned/dcs-food-order/src/app/order/order-form/order-form.component.html',0,import10.ViewEncapsulation.None,styles_OrderFormComponent,{})); }
  return new _View_OrderFormComponent0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_OrderFormComponent1:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo([
    import17.FormGroupDirective,
    import18.ControlContainer,
    import19.NgControlStatusGroup
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import20.SelectControlValueAccessor,
    import21.NG_VALUE_ACCESSOR,
    import22.FormControlName,
    import23.NgControl,
    import19.NgControlStatus
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import20.NgSelectOption,
    import24.NgSelectMultipleOption
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import12.TemplateRef,
    import13.NgFor
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import20.SelectControlValueAccessor,
    import21.NG_VALUE_ACCESSOR,
    import22.FormControlName,
    import23.NgControl,
    import19.NgControlStatus
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import20.NgSelectOption,
    import24.NgSelectMultipleOption
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import12.TemplateRef,
    import13.NgFor
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import25.DefaultValueAccessor,
    import26.NumberValueAccessor,
    import21.NG_VALUE_ACCESSOR,
    import22.FormControlName,
    import23.NgControl,
    import19.NgControlStatus
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class _View_OrderFormComponent1 extends import3.DebugAppView<any> {
  _el_0:any;
  _FormGroupDirective_0_3:import27.Wrapper_FormGroupDirective;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import28.Wrapper_NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _SelectControlValueAccessor_4_3:import29.Wrapper_SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_4_4:any[];
  _FormControlName_4_5:import30.Wrapper_FormControlName;
  _NgControl_4_6:any;
  _NgControlStatus_4_7:import28.Wrapper_NgControlStatus;
  _text_5:any;
  _el_6:any;
  _NgSelectOption_6_3:import29.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_6_4:import31.Wrapper_NgSelectMultipleOption;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import6.AppElement;
  _TemplateRef_8_5:any;
  _NgFor_8_6:import14.Wrapper_NgFor;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _SelectControlValueAccessor_14_3:import29.Wrapper_SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_14_4:any[];
  _FormControlName_14_5:import30.Wrapper_FormControlName;
  _NgControl_14_6:any;
  _NgControlStatus_14_7:import28.Wrapper_NgControlStatus;
  _text_15:any;
  _el_16:any;
  _NgSelectOption_16_3:import29.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_16_4:import31.Wrapper_NgSelectMultipleOption;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import6.AppElement;
  _TemplateRef_18_5:any;
  _NgFor_18_6:import14.Wrapper_NgFor;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _DefaultValueAccessor_24_3:import32.Wrapper_DefaultValueAccessor;
  _NumberValueAccessor_24_4:import33.Wrapper_NumberValueAccessor;
  _NG_VALUE_ACCESSOR_24_5:any[];
  _FormControlName_24_6:import30.Wrapper_FormControlName;
  _NgControl_24_7:any;
  _NgControlStatus_24_8:import28.Wrapper_NgControlStatus;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  /*private*/ _expr_68:any;
  _pipe_dcsPrice_0_0:any;
  /*private*/ _expr_70:any;
  _pipe_dcsPrice_0_1:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement) {
    super(_View_OrderFormComponent1,renderType_OrderFormComponent,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OrderFormComponent1);
    this._expr_68 = import1.UNINITIALIZED;
    this._expr_70 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = import2.createRenderElement(this.renderer,(null as any),'tr',import2.EMPTY_INLINE_ARRAY,this.debug(0,14,4));
    this._FormGroupDirective_0_3 = new import27.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_0_4 = this._FormGroupDirective_0_3.context;
    this._NgControlStatusGroup_0_5 = new import28.Wrapper_NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',this.debug(1,14,93));
    this._el_2 = import2.createRenderElement(this.renderer,this._el_0,'td',import2.EMPTY_INLINE_ARRAY,this.debug(2,15,6));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',this.debug(3,15,10));
    this._el_4 = import2.createRenderElement(this.renderer,this._el_2,'select',new import2.InlineArray4(4,'class','form-control','formControlName','user'),this.debug(4,16,8));
    this._SelectControlValueAccessor_4_3 = new import29.Wrapper_SelectControlValueAccessor(this.renderer,new import34.ElementRef(this._el_4));
    this._NG_VALUE_ACCESSOR_4_4 = [this._SelectControlValueAccessor_4_3.context];
    this._FormControlName_4_5 = new import30.Wrapper_FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_4_4);
    this._NgControl_4_6 = this._FormControlName_4_5.context;
    this._NgControlStatus_4_7 = new import28.Wrapper_NgControlStatus(this._NgControl_4_6);
    this._text_5 = this.renderer.createText(this._el_4,'\n          ',this.debug(5,16,60));
    this._el_6 = import2.createRenderElement(this.renderer,this._el_4,'option',import2.EMPTY_INLINE_ARRAY,this.debug(6,17,10));
    this._NgSelectOption_6_3 = new import29.Wrapper_NgSelectOption(new import34.ElementRef(this._el_6),this.renderer,this._SelectControlValueAccessor_4_3.context);
    this._NgSelectMultipleOption_6_4 = new import31.Wrapper_NgSelectMultipleOption(new import34.ElementRef(this._el_6),this.renderer,(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n          ',this.debug(7,17,27));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_4,this.debug(8,18,10));
    this._appEl_8 = new import6.AppElement(8,4,this,this._anchor_8);
    this._TemplateRef_8_5 = new import12.TemplateRef_(this._appEl_8,viewFactory_OrderFormComponent2);
    this._NgFor_8_6 = new import14.Wrapper_NgFor(this._appEl_8.vcRef,this._TemplateRef_8_5,this.parent.parentInjector.get(import16.IterableDiffers),this.parent.ref);
    this._text_9 = this.renderer.createText(this._el_4,'\n        ',this.debug(9,18,79));
    this._text_10 = this.renderer.createText(this._el_2,'\n      ',this.debug(10,19,17));
    this._text_11 = this.renderer.createText(this._el_0,'\n\n      ',this.debug(11,20,11));
    this._el_12 = import2.createRenderElement(this.renderer,this._el_0,'td',import2.EMPTY_INLINE_ARRAY,this.debug(12,22,6));
    this._text_13 = this.renderer.createText(this._el_12,'\n        ',this.debug(13,22,10));
    this._el_14 = import2.createRenderElement(this.renderer,this._el_12,'select',new import2.InlineArray4(4,'class','form-control','formControlName','productId'),this.debug(14,23,8));
    this._SelectControlValueAccessor_14_3 = new import29.Wrapper_SelectControlValueAccessor(this.renderer,new import34.ElementRef(this._el_14));
    this._NG_VALUE_ACCESSOR_14_4 = [this._SelectControlValueAccessor_14_3.context];
    this._FormControlName_14_5 = new import30.Wrapper_FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_14_4);
    this._NgControl_14_6 = this._FormControlName_14_5.context;
    this._NgControlStatus_14_7 = new import28.Wrapper_NgControlStatus(this._NgControl_14_6);
    this._text_15 = this.renderer.createText(this._el_14,'\n          ',this.debug(15,23,65));
    this._el_16 = import2.createRenderElement(this.renderer,this._el_14,'option',import2.EMPTY_INLINE_ARRAY,this.debug(16,24,10));
    this._NgSelectOption_16_3 = new import29.Wrapper_NgSelectOption(new import34.ElementRef(this._el_16),this.renderer,this._SelectControlValueAccessor_14_3.context);
    this._NgSelectMultipleOption_16_4 = new import31.Wrapper_NgSelectMultipleOption(new import34.ElementRef(this._el_16),this.renderer,(null as any));
    this._text_17 = this.renderer.createText(this._el_14,'\n          ',this.debug(17,24,27));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_14,this.debug(18,25,10));
    this._appEl_18 = new import6.AppElement(18,14,this,this._anchor_18);
    this._TemplateRef_18_5 = new import12.TemplateRef_(this._appEl_18,viewFactory_OrderFormComponent3);
    this._NgFor_18_6 = new import14.Wrapper_NgFor(this._appEl_18.vcRef,this._TemplateRef_18_5,this.parent.parentInjector.get(import16.IterableDiffers),this.parent.ref);
    this._text_19 = this.renderer.createText(this._el_14,'\n        ',this.debug(19,25,114));
    this._text_20 = this.renderer.createText(this._el_12,'\n      ',this.debug(20,26,17));
    this._text_21 = this.renderer.createText(this._el_0,'\n\n      ',this.debug(21,27,11));
    this._el_22 = import2.createRenderElement(this.renderer,this._el_0,'td',import2.EMPTY_INLINE_ARRAY,this.debug(22,29,6));
    this._text_23 = this.renderer.createText(this._el_22,'\n        ',this.debug(23,29,10));
    this._el_24 = import2.createRenderElement(this.renderer,this._el_22,'input',new import2.InlineArray8(8,'class','form-control','formControlName','numberOfProducts','min','0','type','number'),this.debug(24,30,8));
    this._DefaultValueAccessor_24_3 = new import32.Wrapper_DefaultValueAccessor(this.renderer,new import34.ElementRef(this._el_24));
    this._NumberValueAccessor_24_4 = new import33.Wrapper_NumberValueAccessor(this.renderer,new import34.ElementRef(this._el_24));
    this._NG_VALUE_ACCESSOR_24_5 = [
      this._DefaultValueAccessor_24_3.context,
      this._NumberValueAccessor_24_4.context
    ]
    ;
    this._FormControlName_24_6 = new import30.Wrapper_FormControlName(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_24_5);
    this._NgControl_24_7 = this._FormControlName_24_6.context;
    this._NgControlStatus_24_8 = new import28.Wrapper_NgControlStatus(this._NgControl_24_7);
    this._text_25 = this.renderer.createText(this._el_22,'\n      ',this.debug(25,30,93));
    this._text_26 = this.renderer.createText(this._el_0,'\n\n      ',this.debug(26,31,11));
    this._el_27 = import2.createRenderElement(this.renderer,this._el_0,'td',import2.EMPTY_INLINE_ARRAY,this.debug(27,33,6));
    this._text_28 = this.renderer.createText(this._el_27,'',this.debug(28,33,10));
    this._text_29 = this.renderer.createText(this._el_0,'\n      ',this.debug(29,33,70));
    this._el_30 = import2.createRenderElement(this.renderer,this._el_0,'td',import2.EMPTY_INLINE_ARRAY,this.debug(30,34,6));
    this._text_31 = this.renderer.createText(this._el_30,'',this.debug(31,34,10));
    this._text_32 = this.renderer.createText(this._el_0,'\n\n      ',this.debug(32,34,59));
    this._el_33 = import2.createRenderElement(this.renderer,this._el_0,'td',import2.EMPTY_INLINE_ARRAY,this.debug(33,36,6));
    this._text_34 = this.renderer.createText(this._el_33,'\n        ',this.debug(34,36,10));
    this._el_35 = import2.createRenderElement(this.renderer,this._el_33,'button',new import2.InlineArray4(4,'class','btn btn-danger','type','button'),this.debug(35,37,8));
    this._text_36 = this.renderer.createText(this._el_35,'Delete Item',this.debug(36,37,77));
    this._text_37 = this.renderer.createText(this._el_33,'\n      ',this.debug(37,37,97));
    this._text_38 = this.renderer.createText(this._el_0,'\n    ',this.debug(38,38,11));
    var disposable_0:Function = this.renderer.listen(this._el_0,'submit',this.eventHandler(this._handle_submit_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'reset',this.eventHandler(this._handle_reset_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_4,'change',this.eventHandler(this._handle_change_4_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_4,'blur',this.eventHandler(this._handle_blur_4_1.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_14,'change',this.eventHandler(this._handle_change_14_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_14,'blur',this.eventHandler(this._handle_blur_14_1.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_24,'input',this.eventHandler(this._handle_input_24_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_24,'blur',this.eventHandler(this._handle_blur_24_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_24,'change',this.eventHandler(this._handle_change_24_2.bind(this)));
    this._pipe_dcsPrice_0_0 = import2.pureProxy1((<_View_OrderFormComponent0>this.parent)._pipe_dcsPrice_0.transform.bind((<_View_OrderFormComponent0>this.parent)._pipe_dcsPrice_0));
    this._pipe_dcsPrice_0_1 = import2.pureProxy1((<_View_OrderFormComponent0>this.parent)._pipe_dcsPrice_0.transform.bind((<_View_OrderFormComponent0>this.parent)._pipe_dcsPrice_0));
    var disposable_9:Function = this.renderer.listen(this._el_35,'click',this.eventHandler(this._handle_click_35_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.NgSelectOption) && (6 === requestNodeIndex))) { return this._NgSelectOption_6_3.context; }
    if (((token === import24.NgSelectMultipleOption) && (6 === requestNodeIndex))) { return this._NgSelectMultipleOption_6_4.context; }
    if (((token === import12.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import13.NgFor) && (8 === requestNodeIndex))) { return this._NgFor_8_6.context; }
    if (((token === import20.SelectControlValueAccessor) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._SelectControlValueAccessor_4_3.context; }
    if (((token === import21.NG_VALUE_ACCESSOR) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._NG_VALUE_ACCESSOR_4_4; }
    if (((token === import22.FormControlName) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._FormControlName_4_5.context; }
    if (((token === import23.NgControl) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._NgControl_4_6; }
    if (((token === import19.NgControlStatus) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._NgControlStatus_4_7.context; }
    if (((token === import20.NgSelectOption) && (16 === requestNodeIndex))) { return this._NgSelectOption_16_3.context; }
    if (((token === import24.NgSelectMultipleOption) && (16 === requestNodeIndex))) { return this._NgSelectMultipleOption_16_4.context; }
    if (((token === import12.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import13.NgFor) && (18 === requestNodeIndex))) { return this._NgFor_18_6.context; }
    if (((token === import20.SelectControlValueAccessor) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._SelectControlValueAccessor_14_3.context; }
    if (((token === import21.NG_VALUE_ACCESSOR) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NG_VALUE_ACCESSOR_14_4; }
    if (((token === import22.FormControlName) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._FormControlName_14_5.context; }
    if (((token === import23.NgControl) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgControl_14_6; }
    if (((token === import19.NgControlStatus) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgControlStatus_14_7.context; }
    if (((token === import25.DefaultValueAccessor) && (24 === requestNodeIndex))) { return this._DefaultValueAccessor_24_3.context; }
    if (((token === import26.NumberValueAccessor) && (24 === requestNodeIndex))) { return this._NumberValueAccessor_24_4.context; }
    if (((token === import21.NG_VALUE_ACCESSOR) && (24 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_24_5; }
    if (((token === import22.FormControlName) && (24 === requestNodeIndex))) { return this._FormControlName_24_6.context; }
    if (((token === import23.NgControl) && (24 === requestNodeIndex))) { return this._NgControl_24_7; }
    if (((token === import19.NgControlStatus) && (24 === requestNodeIndex))) { return this._NgControlStatus_24_8.context; }
    if (((token === import17.FormGroupDirective) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._FormGroupDirective_0_3.context; }
    if (((token === import18.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._ControlContainer_0_4; }
    if (((token === import19.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgControlStatusGroup_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    this.debug(0,14,66);
    const currVal_0_0_0:any = this.context.$implicit;
    this._FormGroupDirective_0_3.check_form(currVal_0_0_0,throwOnChange,false);
    this._FormGroupDirective_0_3.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.debug(0,14,4);
    this._NgControlStatusGroup_0_5.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.debug(4,16,8);
    this._SelectControlValueAccessor_4_3.detectChangesInInputProps(this,this._el_4,throwOnChange);
    this.debug(4,16,37);
    const currVal_4_1_0:any = 'user';
    this._FormControlName_4_5.check_name(currVal_4_1_0,throwOnChange,false);
    this._FormControlName_4_5.detectChangesInInputProps(this,this._el_4,throwOnChange);
    this.debug(4,16,8);
    this._NgControlStatus_4_7.detectChangesInInputProps(this,this._el_4,throwOnChange);
    this.debug(6,17,10);
    this._NgSelectOption_6_3.detectChangesInInputProps(this,this._el_6,throwOnChange);
    this._NgSelectMultipleOption_6_4.detectChangesInInputProps(this,this._el_6,throwOnChange);
    this.debug(8,18,33);
    const currVal_8_0_0:any = this.parent.context.users;
    this._NgFor_8_6.check_ngForOf(currVal_8_0_0,throwOnChange,false);
    this._NgFor_8_6.detectChangesInInputProps(this,this._anchor_8,throwOnChange);
    this.debug(14,23,8);
    this._SelectControlValueAccessor_14_3.detectChangesInInputProps(this,this._el_14,throwOnChange);
    this.debug(14,23,37);
    const currVal_14_1_0:any = 'productId';
    this._FormControlName_14_5.check_name(currVal_14_1_0,throwOnChange,false);
    this._FormControlName_14_5.detectChangesInInputProps(this,this._el_14,throwOnChange);
    this.debug(14,23,8);
    this._NgControlStatus_14_7.detectChangesInInputProps(this,this._el_14,throwOnChange);
    this.debug(16,24,10);
    this._NgSelectOption_16_3.detectChangesInInputProps(this,this._el_16,throwOnChange);
    this._NgSelectMultipleOption_16_4.detectChangesInInputProps(this,this._el_16,throwOnChange);
    this.debug(18,25,46);
    const currVal_18_0_0:any = this.parent.context.products;
    this._NgFor_18_6.check_ngForOf(currVal_18_0_0,throwOnChange,false);
    this._NgFor_18_6.detectChangesInInputProps(this,this._anchor_18,throwOnChange);
    this.debug(24,30,8);
    this._DefaultValueAccessor_24_3.detectChangesInInputProps(this,this._el_24,throwOnChange);
    this._NumberValueAccessor_24_4.detectChangesInInputProps(this,this._el_24,throwOnChange);
    this.debug(24,30,58);
    const currVal_24_2_0:any = 'numberOfProducts';
    this._FormControlName_24_6.check_name(currVal_24_2_0,throwOnChange,false);
    this._FormControlName_24_6.detectChangesInInputProps(this,this._el_24,throwOnChange);
    this.debug(24,30,8);
    this._NgControlStatus_24_8.detectChangesInInputProps(this,this._el_24,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._FormGroupDirective_0_3.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this._NgControlStatusGroup_0_5.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this._SelectControlValueAccessor_4_3.detectChangesInHostProps(this,this._el_4,throwOnChange);
    this._FormControlName_4_5.detectChangesInHostProps(this,this._el_4,throwOnChange);
    this._NgControlStatus_4_7.detectChangesInHostProps(this,this._el_4,throwOnChange);
    this._NgSelectOption_6_3.detectChangesInHostProps(this,this._el_6,throwOnChange);
    this._NgSelectMultipleOption_6_4.detectChangesInHostProps(this,this._el_6,throwOnChange);
    this._SelectControlValueAccessor_14_3.detectChangesInHostProps(this,this._el_14,throwOnChange);
    this._FormControlName_14_5.detectChangesInHostProps(this,this._el_14,throwOnChange);
    this._NgControlStatus_14_7.detectChangesInHostProps(this,this._el_14,throwOnChange);
    this._NgSelectOption_16_3.detectChangesInHostProps(this,this._el_16,throwOnChange);
    this._NgSelectMultipleOption_16_4.detectChangesInHostProps(this,this._el_16,throwOnChange);
    this._DefaultValueAccessor_24_3.detectChangesInHostProps(this,this._el_24,throwOnChange);
    this._NumberValueAccessor_24_4.detectChangesInHostProps(this,this._el_24,throwOnChange);
    this._FormControlName_24_6.detectChangesInHostProps(this,this._el_24,throwOnChange);
    this._NgControlStatus_24_8.detectChangesInHostProps(this,this._el_24,throwOnChange);
    this.debug(28,33,10);
    valUnwrapper.reset();
    const currVal_68:any = import2.interpolate(1,'',valUnwrapper.unwrap(import2.castByValue(this._pipe_dcsPrice_0_0,(<_View_OrderFormComponent0>this.parent)._pipe_dcsPrice_0.transform)(this.parent.context.getPrice(this.context.$implicit.value.productId))),'');
    if ((valUnwrapper.hasWrappedValue || import2.checkBinding(throwOnChange,this._expr_68,currVal_68))) {
      this.renderer.setText(this._text_28,currVal_68);
      this._expr_68 = currVal_68;
    }
    this.debug(31,34,10);
    valUnwrapper.reset();
    const currVal_70:any = import2.interpolate(1,'',valUnwrapper.unwrap(import2.castByValue(this._pipe_dcsPrice_0_1,(<_View_OrderFormComponent0>this.parent)._pipe_dcsPrice_0.transform)(this.parent.context.getTotalPrice(this.context.$implicit))),'');
    if ((valUnwrapper.hasWrappedValue || import2.checkBinding(throwOnChange,this._expr_70,currVal_70))) {
      this.renderer.setText(this._text_31,currVal_70);
      this._expr_70 = currVal_70;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(6,17,10);
    this._NgSelectOption_6_3.context.ngOnDestroy();
    this._NgSelectMultipleOption_6_4.context.ngOnDestroy();
    this.debug(4,16,8);
    this._FormControlName_4_5.context.ngOnDestroy();
    this.debug(16,24,10);
    this._NgSelectOption_16_3.context.ngOnDestroy();
    this._NgSelectMultipleOption_16_4.context.ngOnDestroy();
    this.debug(14,23,8);
    this._FormControlName_14_5.context.ngOnDestroy();
    this.debug(24,30,8);
    this._FormControlName_24_6.context.ngOnDestroy();
  }
  private _handle_submit_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(0,14,4);
    const pd_0_0:any = ((<any>this._FormGroupDirective_0_3.context.onSubmit($event)) !== false);
    return (true && pd_0_0);
  }
  private _handle_reset_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(0,14,4);
    const pd_0_0:any = ((<any>this._FormGroupDirective_0_3.context.onReset()) !== false);
    return (true && pd_0_0);
  }
  private _handle_change_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(4,16,8);
    const pd_4_0:any = ((<any>this._SelectControlValueAccessor_4_3.context.onChange($event.target.value)) !== false);
    return (true && pd_4_0);
  }
  private _handle_blur_4_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(4,16,8);
    const pd_4_0:any = ((<any>this._SelectControlValueAccessor_4_3.context.onTouched()) !== false);
    return (true && pd_4_0);
  }
  private _handle_change_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(14,23,8);
    const pd_14_0:any = ((<any>this._SelectControlValueAccessor_14_3.context.onChange($event.target.value)) !== false);
    return (true && pd_14_0);
  }
  private _handle_blur_14_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(14,23,8);
    const pd_14_0:any = ((<any>this._SelectControlValueAccessor_14_3.context.onTouched()) !== false);
    return (true && pd_14_0);
  }
  private _handle_input_24_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(24,30,8);
    const pd_24_0:any = ((<any>this._DefaultValueAccessor_24_3.context.onChange($event.target.value)) !== false);
    this.debug(24,30,8);
    const pd_24_1:any = ((<any>this._NumberValueAccessor_24_4.context.onChange($event.target.value)) !== false);
    return ((true && pd_24_0) && pd_24_1);
  }
  private _handle_blur_24_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(24,30,8);
    const pd_24_0:any = ((<any>this._DefaultValueAccessor_24_3.context.onTouched()) !== false);
    this.debug(24,30,8);
    const pd_24_1:any = ((<any>this._NumberValueAccessor_24_4.context.onTouched()) !== false);
    return ((true && pd_24_0) && pd_24_1);
  }
  private _handle_change_24_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(24,30,8);
    const pd_24_0:any = ((<any>this._NumberValueAccessor_24_4.context.onChange($event.target.value)) !== false);
    return (true && pd_24_0);
  }
  private _handle_click_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(35,37,53);
    const pd_35_0:any = ((<any>this.parent.context.deleteItem(this.context.index)) !== false);
    return (true && pd_35_0);
  }
}
function viewFactory_OrderFormComponent1(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement):import3.AppView<any> {
  return new _View_OrderFormComponent1(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_OrderFormComponent2:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo([
    import20.NgSelectOption,
    import24.NgSelectMultipleOption
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class _View_OrderFormComponent2 extends import3.DebugAppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import29.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_0_4:import31.Wrapper_NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement) {
    super(_View_OrderFormComponent2,renderType_OrderFormComponent,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OrderFormComponent2);
    this._expr_4 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = import2.createRenderElement(this.renderer,(null as any),'option',import2.EMPTY_INLINE_ARRAY,this.debug(0,18,10));
    this._NgSelectOption_0_3 = new import29.Wrapper_NgSelectOption(new import34.ElementRef(this._el_0),this.renderer,(<_View_OrderFormComponent1>this.parent)._SelectControlValueAccessor_4_3.context);
    this._NgSelectMultipleOption_0_4 = new import31.Wrapper_NgSelectMultipleOption(new import34.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',this.debug(1,18,60));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3.context; }
    if (((token === import24.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,18,18);
    const currVal_0_0_0:any = this.context.$implicit;
    this._NgSelectOption_0_3.check_value(currVal_0_0_0,throwOnChange,false);
    this._NgSelectOption_0_3.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.debug(0,18,18);
    const currVal_0_1_0:any = this.context.$implicit;
    this._NgSelectMultipleOption_0_4.check_value(currVal_0_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._NgSelectOption_0_3.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this._NgSelectMultipleOption_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.debug(1,18,60);
    const currVal_4:any = import2.interpolate(1,'',this.context.$implicit,'');
    if (import2.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(0,18,10);
    this._NgSelectOption_0_3.context.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.context.ngOnDestroy();
  }
}
function viewFactory_OrderFormComponent2(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement):import3.AppView<any> {
  return new _View_OrderFormComponent2(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_OrderFormComponent3:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo([
    import20.NgSelectOption,
    import24.NgSelectMultipleOption
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class _View_OrderFormComponent3 extends import3.DebugAppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import29.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_0_4:import31.Wrapper_NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement) {
    super(_View_OrderFormComponent3,renderType_OrderFormComponent,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OrderFormComponent3);
    this._expr_4 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = import2.createRenderElement(this.renderer,(null as any),'option',import2.EMPTY_INLINE_ARRAY,this.debug(0,25,10));
    this._NgSelectOption_0_3 = new import29.Wrapper_NgSelectOption(new import34.ElementRef(this._el_0),this.renderer,(<_View_OrderFormComponent1>this.parent)._SelectControlValueAccessor_14_3.context);
    this._NgSelectMultipleOption_0_4 = new import31.Wrapper_NgSelectMultipleOption(new import34.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',this.debug(1,25,79));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3.context; }
    if (((token === import24.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,25,18);
    const currVal_0_0_0:any = this.context.$implicit.get('id');
    this._NgSelectOption_0_3.check_value(currVal_0_0_0,throwOnChange,false);
    this._NgSelectOption_0_3.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.debug(0,25,18);
    const currVal_0_1_0:any = this.context.$implicit.get('id');
    this._NgSelectMultipleOption_0_4.check_value(currVal_0_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._NgSelectOption_0_3.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this._NgSelectMultipleOption_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.debug(1,25,79);
    const currVal_4:any = import2.interpolate(1,'',this.context.$implicit.get('label'),'');
    if (import2.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_1,currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(0,25,10);
    this._NgSelectOption_0_3.context.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.context.ngOnDestroy();
  }
}
function viewFactory_OrderFormComponent3(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement):import3.AppView<any> {
  return new _View_OrderFormComponent3(viewUtils,parentInjector,declarationEl);
}