/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './order-totals.component';
import * as import1 from '@angular/core/src/change_detection/change_detection';
import * as import2 from '@angular/core/src/linker/view_utils';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/debug_context';
import * as import5 from '@angular/core/src/render/api';
import * as import6 from '@angular/core/src/linker/element';
import * as import7 from '@angular/core/src/di/injector';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/core/src/linker/template_ref';
import * as import12 from '@angular/common/src/directives/ng_for';
import * as import13 from '../../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import14 from '../../shared/pipes/Price.pipe';
import * as import15 from '@angular/core/src/change_detection/differs/iterable_differs';
export class Wrapper_OrderTotalsComponent {
  context:import0.OrderTotalsComponent;
  changed:boolean;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor() {
    this.changed = false;
    this.context = new import0.OrderTotalsComponent();
    this._expr_0 = import1.UNINITIALIZED;
    this._expr_1 = import1.UNINITIALIZED;
  }
  check_orderTotalsByUser(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._expr_0,currValue))) {
      this.changed = true;
      this.context.orderTotalsByUser = currValue;
      this._expr_0 = currValue;
    }
  }
  check_orderTotal(currValue:any,throwOnChange:boolean,forceUpdate:boolean):void {
    if ((forceUpdate || import2.checkBinding(throwOnChange,this._expr_1,currValue))) {
      this.changed = true;
      this.context.orderTotal = currValue;
      this._expr_1 = currValue;
    }
  }
  detectChangesInInputProps(view:import3.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import3.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
const nodeDebugInfos_OrderTotalsComponent_Host0:import4.StaticNodeDebugInfo[] = [new import4.StaticNodeDebugInfo([import0.OrderTotalsComponent],import0.OrderTotalsComponent,{})];
var renderType_OrderTotalsComponent_Host:import5.RenderComponentType = (null as any);
class _View_OrderTotalsComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import6.AppElement;
  _OrderTotalsComponent_0_4:Wrapper_OrderTotalsComponent;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement) {
    super(_View_OrderTotalsComponent_Host0,renderType_OrderTotalsComponent_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OrderTotalsComponent_Host0);
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = import2.selectOrCreateRenderHostElement(this.renderer,'dcs-order-totals',import2.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import6.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_OrderTotalsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._OrderTotalsComponent_0_4 = new Wrapper_OrderTotalsComponent();
    this._appEl_0.initComponent(this._OrderTotalsComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._OrderTotalsComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.OrderTotalsComponent) && (0 === requestNodeIndex))) { return this._OrderTotalsComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._OrderTotalsComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._OrderTotalsComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_OrderTotalsComponent_Host0(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement):import3.AppView<any> {
  if ((renderType_OrderTotalsComponent_Host === (null as any))) { (renderType_OrderTotalsComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_OrderTotalsComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const OrderTotalsComponentNgFactory:import10.ComponentFactory<import0.OrderTotalsComponent> = new import10.ComponentFactory<import0.OrderTotalsComponent>('dcs-order-totals',viewFactory_OrderTotalsComponent_Host0,import0.OrderTotalsComponent);
const styles_OrderTotalsComponent:any[] = ([] as any[]);
const nodeDebugInfos_OrderTotalsComponent0:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo([
    import11.TemplateRef,
    import12.NgFor
  ]
  ,(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_OrderTotalsComponent:import5.RenderComponentType = (null as any);
class _View_OrderTotalsComponent0 extends import3.DebugAppView<import0.OrderTotalsComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import6.AppElement;
  _TemplateRef_16_5:any;
  _NgFor_16_6:import13.Wrapper_NgFor;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _pipe_dcsPrice_0:import14.PricePipe;
  /*private*/ _expr_32:any;
  _pipe_dcsPrice_0_1:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement) {
    super(_View_OrderTotalsComponent0,renderType_OrderTotalsComponent,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OrderTotalsComponent0);
    this._expr_32 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import6.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import2.createRenderElement(this.renderer,parentRenderNode,'table',new import2.InlineArray2(2,'class','table table-striped table-bordered table-hover'),this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',this.debug(1,0,62));
    this._el_2 = import2.createRenderElement(this.renderer,this._el_0,'thead',import2.EMPTY_INLINE_ARRAY,this.debug(2,1,2));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',this.debug(3,1,9));
    this._el_4 = import2.createRenderElement(this.renderer,this._el_2,'tr',import2.EMPTY_INLINE_ARRAY,this.debug(4,2,4));
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',this.debug(5,2,8));
    this._el_6 = import2.createRenderElement(this.renderer,this._el_4,'th',import2.EMPTY_INLINE_ARRAY,this.debug(6,3,6));
    this._text_7 = this.renderer.createText(this._el_6,'User',this.debug(7,3,10));
    this._text_8 = this.renderer.createText(this._el_4,'\n      ',this.debug(8,3,19));
    this._el_9 = import2.createRenderElement(this.renderer,this._el_4,'th',import2.EMPTY_INLINE_ARRAY,this.debug(9,4,6));
    this._text_10 = this.renderer.createText(this._el_9,'Total Payment',this.debug(10,4,10));
    this._text_11 = this.renderer.createText(this._el_4,'\n    ',this.debug(11,4,28));
    this._text_12 = this.renderer.createText(this._el_2,'\n  ',this.debug(12,5,9));
    this._text_13 = this.renderer.createText(this._el_0,'\n\n  ',this.debug(13,6,10));
    this._el_14 = import2.createRenderElement(this.renderer,this._el_0,'tbody',import2.EMPTY_INLINE_ARRAY,this.debug(14,8,2));
    this._text_15 = this.renderer.createText(this._el_14,'\n\n    ',this.debug(15,8,9));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_14,this.debug(16,10,4));
    this._appEl_16 = new import6.AppElement(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import11.TemplateRef_(this._appEl_16,viewFactory_OrderTotalsComponent1);
    this._NgFor_16_6 = new import13.Wrapper_NgFor(this._appEl_16.vcRef,this._TemplateRef_16_5,this.parentInjector.get(import15.IterableDiffers),this.ref);
    this._text_17 = this.renderer.createText(this._el_14,'\n\n    ',this.debug(17,13,9));
    this._el_18 = import2.createRenderElement(this.renderer,this._el_14,'tr',import2.EMPTY_INLINE_ARRAY,this.debug(18,15,4));
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',this.debug(19,15,8));
    this._el_20 = import2.createRenderElement(this.renderer,this._el_18,'th',import2.EMPTY_INLINE_ARRAY,this.debug(20,16,6));
    this._text_21 = this.renderer.createText(this._el_20,'TOTAL',this.debug(21,16,10));
    this._text_22 = this.renderer.createText(this._el_18,'\n      ',this.debug(22,16,20));
    this._el_23 = import2.createRenderElement(this.renderer,this._el_18,'th',import2.EMPTY_INLINE_ARRAY,this.debug(23,17,6));
    this._text_24 = this.renderer.createText(this._el_23,'',this.debug(24,17,10));
    this._text_25 = this.renderer.createText(this._el_18,'\n    ',this.debug(25,17,42));
    this._text_26 = this.renderer.createText(this._el_14,'\n\n',this.debug(26,18,9));
    this._text_27 = this.renderer.createText(parentRenderNode,'\n',this.debug(27,20,8));
    this.debug((null as any),(null as any),(null as any));
    this._pipe_dcsPrice_0 = new import14.PricePipe();
    this._pipe_dcsPrice_0_1 = import2.pureProxy1(this._pipe_dcsPrice_0.transform.bind(this._pipe_dcsPrice_0));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import11.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import12.NgFor) && (16 === requestNodeIndex))) { return this._NgFor_16_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    this.debug(16,10,8);
    const currVal_16_0_0:any = this.context.orderTotalsByUser;
    this._NgFor_16_6.check_ngForOf(currVal_16_0_0,throwOnChange,false);
    this._NgFor_16_6.detectChangesInInputProps(this,this._anchor_16,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(24,17,10);
    valUnwrapper.reset();
    const currVal_32:any = import2.interpolate(1,'',valUnwrapper.unwrap(import2.castByValue(this._pipe_dcsPrice_0_1,this._pipe_dcsPrice_0.transform)(this.context.orderTotal)),'');
    if ((valUnwrapper.hasWrappedValue || import2.checkBinding(throwOnChange,this._expr_32,currVal_32))) {
      this.renderer.setText(this._text_24,currVal_32);
      this._expr_32 = currVal_32;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_OrderTotalsComponent0(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement):import3.AppView<import0.OrderTotalsComponent> {
  if ((renderType_OrderTotalsComponent === (null as any))) { (renderType_OrderTotalsComponent = viewUtils.createRenderComponentType('/Users/peterdickten/versioned/dcs-food-order/src/app/order/order-totals/order-totals.component.html',0,import9.ViewEncapsulation.None,styles_OrderTotalsComponent,{})); }
  return new _View_OrderTotalsComponent0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_OrderTotalsComponent1:import4.StaticNodeDebugInfo[] = [
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import4.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
class _View_OrderTotalsComponent1 extends import3.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  _pipe_dcsPrice_0_0:any;
  constructor(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement) {
    super(_View_OrderTotalsComponent1,renderType_OrderTotalsComponent,import8.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import1.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_OrderTotalsComponent1);
    this._expr_8 = import1.UNINITIALIZED;
    this._expr_9 = import1.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = import2.createRenderElement(this.renderer,(null as any),'tr',import2.EMPTY_INLINE_ARRAY,this.debug(0,10,4));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',this.debug(1,10,47));
    this._el_2 = import2.createRenderElement(this.renderer,this._el_0,'td',import2.EMPTY_INLINE_ARRAY,this.debug(2,11,6));
    this._text_3 = this.renderer.createText(this._el_2,'',this.debug(3,11,10));
    this._text_4 = this.renderer.createText(this._el_0,'\n      ',this.debug(4,11,28));
    this._el_5 = import2.createRenderElement(this.renderer,this._el_0,'td',import2.EMPTY_INLINE_ARRAY,this.debug(5,12,6));
    this._text_6 = this.renderer.createText(this._el_5,'',this.debug(6,12,10));
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',this.debug(7,12,39));
    this._pipe_dcsPrice_0_0 = import2.pureProxy1((<_View_OrderTotalsComponent0>this.parent)._pipe_dcsPrice_0.transform.bind((<_View_OrderTotalsComponent0>this.parent)._pipe_dcsPrice_0));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import1.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(3,11,10);
    const currVal_8:any = import2.interpolate(1,'',this.context.$implicit[0],'');
    if (import2.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_3,currVal_8);
      this._expr_8 = currVal_8;
    }
    this.debug(6,12,10);
    valUnwrapper.reset();
    const currVal_9:any = import2.interpolate(1,'',valUnwrapper.unwrap(import2.castByValue(this._pipe_dcsPrice_0_0,(<_View_OrderTotalsComponent0>this.parent)._pipe_dcsPrice_0.transform)(this.context.$implicit[1])),'');
    if ((valUnwrapper.hasWrappedValue || import2.checkBinding(throwOnChange,this._expr_9,currVal_9))) {
      this.renderer.setText(this._text_6,currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_OrderTotalsComponent1(viewUtils:import2.ViewUtils,parentInjector:import7.Injector,declarationEl:import6.AppElement):import3.AppView<any> {
  return new _View_OrderTotalsComponent1(viewUtils,parentInjector,declarationEl);
}