/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './core.module';
import * as import2 from './rest.service';
import * as import3 from '@angular/core/src/di/injector';
import * as import4 from '@angular/http/src/http';
import * as import5 from '../settings';
class CoreModuleInjector extends import0.NgModuleInjector<import1.CoreModule> {
  _CoreModule_0:import1.CoreModule;
  __RestService_1:import2.RestService;
  constructor(parent:import3.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _RestService_1():import2.RestService {
    if ((this.__RestService_1 == (null as any))) { (this.__RestService_1 = new import2.RestService(this.parent.get(import4.Http),this.parent.get(import5.APP_SETTINGS))); }
    return this.__RestService_1;
  }
  createInternal():import1.CoreModule {
    this._CoreModule_0 = new import1.CoreModule(this.parent.get(import1.CoreModule,(null as any)));
    return this._CoreModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.CoreModule)) { return this._CoreModule_0; }
    if ((token === import2.RestService)) { return this._RestService_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CoreModuleNgFactory:import0.NgModuleFactory<import1.CoreModule> = new import0.NgModuleFactory(CoreModuleInjector,import1.CoreModule);